# Generated by Django 3.2.18 on 2023-02-17 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_item_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
